version: "3.6"
services:
  jboss6:
    build:
      context: ./test
      dockerfile: DockerJBoss6
    container_name: jboss6
    volumes:
      - ./newrelic-agent/build/newrelicJar:/newrelic
    ports:
      - "8080:8080"
  jboss7:
    build:
      context: ./test
      dockerfile: DockerJBoss7
    container_name: jboss7
    volumes:
      - ./newrelic-agent/build/newrelicJar:/newrelic
    ports:
      - "8080:8080"
  wildfly:
    image: quay.io/wildfly/wildfly
    volumes:
      - ./newrelic-agent/build/newrelicJar:/newrelic
    ports:
      - "8080:8080"
      - "9990:9990"
    command: /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0
    environment:
      - JAVA_OPTS=-javaagent:/newrelic/newrelic.jar -Dorg.wildfly.logging.skipLogManagerCheck=true
      - NEW_RELIC_APP_NAME=MyWildflyApp
      - NEW_RELIC_LICENSE_KEY
      - NEW_RELIC_HOST
  wildfly20:
    build:
      context: ./test
      dockerfile: DockerWildfly20
    container_name: wildfly20
    volumes:
      - ./newrelic-agent/build/newrelicJar:/newrelic
    ports:
      - "8080:8080"
      - "9990:9990"
    command: /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0
    environment:
      - JAVA_OPTS=-javaagent:/newrelic/newrelic.jar -Dorg.wildfly.logging.skipLogManagerCheck=true -server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true
      - NEW_RELIC_APP_NAME=MyWildflyApp
      - NEW_RELIC_LICENSE_KEY
      - NEW_RELIC_HOST
  jetty9:
    build:
      context: ./test
      dockerfile: DockerJetty9
    container_name: jetty9
    volumes:
      - ./newrelic-agent/build/newrelicJar:/newrelic
    ports:
      - "8080:8080"
    command: --module=jmx
  tomcat7:
    build:
      context: ./test
      dockerfile: DockerTomcat7
    container_name: tomcat7
    volumes:
      - ./newrelic-agent/build/newrelicJar:/newrelic
    ports:
      - "8080:8080"
  tomcat8:
    build:
      context: ./test
      dockerfile: DockerTomcat8
    container_name: tomcat8
    volumes:
      - ./newrelic-agent/build/newrelicJar:/newrelic
    ports:
      - "8080:8080"
    environment:
      JAVA_HOME: /usr/lib/jvm/java-7-openjdk-amd64
  tomcat9:
    build:
      context: ./test
      dockerfile: DockerTomcat9
    container_name: tomcat9
    volumes:
      - ./newrelic-agent/build/newrelicJar:/newrelic
    ports:
      - "8080:8080"
  websphere:
    build:
      context: ./test
      dockerfile: DockerWebSphereTraditional
    container_name: websphere
    hostname: websphere
    volumes:
      - ./test/WebSpherePassword:/tmp/PASSWORD
      - ./newrelic-agent/build/newrelicJar:/newrelic
    ports:
      - "9443:9443"
      - "9080:9080"
    environment:
      JAVA_HOME: /opt/IBM/WebSphere/AppServer/java/8.0
      PATH: ${PATH}:/opt/IBM/WebSphere/AppServer/java/8.0/bin
  websphere-liberty:
    build:
      context: ./test
      dockerfile: DockerWebSphereLiberty
    container_name: websphere-liberty
    hostname: websphere
    volumes:
      - ./newrelic-agent/build/newrelicJar:/newrelic
    ports:
      - "8080:9080"
  springboot-petclinic:
    build:
      context: ./test/petclinic
    container_name: springboot-petclinic
    volumes:
      - ./newrelic-agent/build/newrelicJar:/newrelic
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
